### PR TITLE
Added additional types "SelectableText", "Icon" and "DropCapText" with usage examples

### PR DESCRIPTION
**Pull request by mrjacobphillips**
I would first like to thank you for the awesome plugin! It was exactly what I was looking for.

For my project I needed type "SelectableText", so I decided to create this pull as others might also be looking for this functionality as well. I also found it a bit odd that the text maxLines property was defaulted to 1 since the native Flutter widgets do not require a value for this property, which I believe would be better suited as the default functionality for this plugin as well.

### CODE REVIEW

**Comment by dengyin2000** [comment]
@mrjacobphillips   sorry to see it so later, could you make some sample usage for these two new widgets in  "example" folder, widget_json.dart and main.dart files. Thanks.

**Comment by mrjacobphillips** [comment]
Absolutely, I have now created these missing examples and added additional type Icon.

**Comment by dengyin2000** [comment]
@mrjacobphillips  thanks, it has been merged.

**Comment by dengyin2000** [comment]
@mrjacobphillips  what's the flutter version you used, i see some compile errors.

1、
image

2、
image

here is my "flutter doctor"

`[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/denny/Work/Utils/flutter
    • Framework revision 68587a0916 (6 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0`

**Comment by mrjacobphillips** [comment]
Oh my apologies, I made these changes using the dev channel.
`[✓] Flutter (Channel dev, v1.15.19, on Mac OS X 10.15 19A573a, locale en-US)
    • Flutter version 1.15.19 at /Users/jacob/Documents/flutter
    • Framework revision 60d0fef17a (10 days ago), 2020-03-09 22:07:34 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)`

**Comment by mrjacobphillips** [comment]
By the looks of things, it should work correctly on the beta channel as well. Stable is just really behind...

**Comment by dengyin2000** [comment]
> By the looks of things, it should work correctly on the beta channel as well. Stable is just really behind...

Ok, I will make it works in latest stable channel.

**Pull request merged**
